### ISSUE TITLE
Plans for integration

### ISSUE THREAD

**Issue by instantkaffee** [earowang/tsibble#2]
Less an issue more a question:

I see great future for this package...

... provided that the tsibble becomes a uniformly accepted input format to the forecast and hts packages. 

The latter ones are the de facto standard to model and predict temporal data. 
The tsibble format might become a new R standard to datamunge with temporal data as the cognitive distance to tools like dplyr, tidyr and purrr seems to be very small.

Can you (maybe in cooperation with Prof. Hyndman) disclose your plans in this regard ?

Thanks so much up to this stage.

**Comment by mitchelloharawild** [comment]
There are plans to add support for tsibble in the forecast and hts packages.
The fasster package (https://github.com/mitchelloharawild/fasster/) uses tsibble object structures in modelling (although needs to be updated to reflect recent UI changes to tsibble).

More to come :smiley:

**Comment by earowang** [comment]
Thanks for your feedback, which is great!

We're in the process of incorporating the forecast output into the tsibble framework (hopefully in the future release v0.2.0).

Users of the `hts` package often find a hard time to specify the hts/gts object for their data, based on  those SO questions. It would be much easier for them to use the tsibble structure for hierarchical and grouped forecasting.

Mitch's `fasster` package is the first attempt to use the tsibble internally in forecasting time series of multiple seasonalities, like sub-daily data, which the `ts` object cannot accomodate.

We hope to get more feedback to help with the tsibble development.
